### ISSUE TITLE
provider doesn't normalize existing resources and keeps applying changes

### ISSUE THREAD

**Issue by rem7** [TGNThump/terraform-provider-vyos#16]
Hi!
It appears that the provider isn't normalizing the existing resources that were previously created, so everytime I run `terraform apply` resources that were already created keep getting marked as "changed" 

Here is a file I've been testing with:
```terraform
terraform {
  required_providers {
    vyos = {
      source = "TGNThump/vyos"
      version = "1.1.0"
    }
  }
}

provider "vyos" {
  endpoint = "https://192.168.100.8"
  api_key  = "api_key"
}

variable "vlan_list" {
  type    = list(map(string))
  default = [ {
    "vlan" = "10"
    "address" = "192.168.10.1/24"
  },{
    "vlan" = "20"
    "address" = "192.168.20.1/24"
  },{
    "vlan" = "30"
    "address" = "192.168.30.1/24"
  } ]
}

resource "vyos_config" "ethernet-eth0-vlans" {
  path  = "interfaces ethernet eth0 vif"
  count = length(var.vlan_list)
  value = jsonencode({
    var.vlan_list[count.index].vlan = {
      address = var.vlan_list[count.index].address
    }
  })
}
```

The first time I run it, the plan I get is: "Plan: 3 to add, 0 to change, 0 to destroy."
If I run it again without any changes, I get: "Plan: 0 to add, 3 to change, 0 to destroy."

**Comment by TGNThump** [comment]
We don't do any noramlisation atm, and relly on the user mirroring the json configuration that vyos uses in it's API. Could you share the plan that shows the drift?

**Comment by JonnyHaystack** [comment]
I too have experienced normalization issues where VyOS's API seems to like turning single element lists into a scalar value instead of a list, so Terraform sees this as a change from the expected state and tries to change it back again (to no effect)

Example:
```tf
# module.vyos.module.config.vyos_config.subnet_dhcp["public"] will be updated in-place
  ~ resource "vyos_config" "subnet_dhcp" {
        id    = "service dhcp-server shared-network-name public subnet 10.0.4.0/24"
      ~ value = jsonencode(
          ~ {
              ~ option    = {
                  ~ name-server    = "10.0.1.110" -> [
                      + "10.0.1.110",
                    ]
                    # (2 unchanged attributes hidden)
                }
                # (3 unchanged attributes hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }
 ```

I have tried to work around this but it requires horrible hacks, as HCL is very annoying in limiting ternary expressions to only have one result type, so I can't do e.g.
```tf
name-server = length(var.dns.name_servers) == 1 ? var.dns.name_servers[0] : var.dns.name_servers
```

It even doesn't allow nesting this within an object and merging, because it still complains about "inconsistent conditional result types".

The only workaround I found that works was as follows, which is incredibly disgusting:

```tf
merge(
  {
    public-key           = peer.pubkey
    persistent-keepalive = "15"
  },
  length(peer.allowed_ips) == 1 ? {
    allowed-ips = peer.allowed_ips[0]
  } : {},
  length(peer.allowed_ips) > 1 ? {
    allowed-ips = peer.allowed_ips
  } : {},
),
```

This is really frustrating from HCL because if it just allowed differing conditional results I would be able to more easily achieve what it is making unnecessarily difficult.

If anyone can think of a better way to make this work, I would be very grateful. I'm not sure if it's possible to solve this on the API side or not, as I imagine that might require knowledge of which paths are arrays vs map vs scalar (which would add undesirable maintenance burden if so).

EDIT: Somewhat improved workaround below, as I realised the later values will overwrite ones from the original object anyway so only one ternary expression needed
```tf
merge(
  {
    allowed-ips          = peer.allowed_ips
    public-key           = peer.pubkey
    persistent-keepalive = "15"
  },
  length(peer.allowed_ips) == 1 ? {
    allowed-ips = peer.allowed_ips[0]
  } : {},
),
```

**Comment by JonnyHaystack** [comment]
Thinking about it a bit, couldn't the provider simply recursively check the `value` object for any arrays that contain single values and convert them to scalar values? Doesn't seem to me like it would cause issues.

On an unrelated note I was also wondering whether the provider can do the `jsonencode()` internally, as I have not yet seen a scenario where you *don't* want/need to wrap the value in `jsonencode()`...
